### PR TITLE
Add suffix parameter

### PR DESCRIPTION
**Pull request by ProDInfo**
Not work properly:

Example:
```
             modelBuilder.Entity<UserRole>(entity =>           
            { 
                entity.HasKey(e => new { e.UserId, e.RoleId });
                
                entity.HasIndex(e => e.RoleId, "IX_UserRoles_RoleId");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.UserRoles)
                    .HasForeignKey(d => d.RoleId);

                entity.HasOne(d => d.User)
                    .WithMany(p => p.UserRoles)
                    .HasForeignKey(d => d.UserId);
            });
```

Change pattern to 

```

       const string statementsInnerBlockPattern = @"(?<=modelBuilder\.Entity<(?<EntityName>.*?)>\((?<EntityParameterName>.*?)\s*=>\s*\{).*?(?:;)(?=\s*\}\);)";

     ...

       const string statementsOuterBlockPattern = @"\s*modelBuilder\.Entity<.*?>\(.*?\s*=>\s*\{.*?;?.*\}\);";
```

### CODE REVIEW

**Review by lauxjpn — CHANGES_REQUESTED** [review]
@ProDInfo Thanks for the PR.
I think it might be better to handle the `});` bug slightly different than you suggested (see PR #3).

The suffix addition is fine.

Please do the following changes, so we can merge this PR:
* Remove the regular expression pattern changes
* Rebase your feature branch on top of the latest `master` branch commit
* Update the _Usage_ section of the `README.md` file

**Comment by ProDInfo** [comment]
I update with suffix parameter and upgrade to net6.0

**Comment by lauxjpn** [comment]
@ProDInfo Please do not just add other fixes or improvements to this PR, as long as they aren't connected to each other. Every individual problem should be addressed in its individual issue or PR.

At this point, this PR is only about the suffix parameter, since the original issue regarding the regular expressions and multiple keys, has already been resolved by #3.

Therefore, please only (force) push your commits regarding the suffix parameter to this PR. They need to be _rebased_ on top of the latest _master_ branch commit, so I can merge it.

For all other fixes/improvements, please either open a new issue, or a new PR (again, with commits rebased on top of the latest _master_ branch commit).

Thanks!

**Comment by ProDInfo** [comment]
Sorry, next time create new PR

**Comment by lauxjpn** [comment]
> Sorry, next time create new PR

No problem. Please now rebase your commits in a way, that only the ones regarding the suffix issue are in your branch, and that your commits are on top of the lastest `master` branch commit (e.g. by using an _interactive rebase_ or by _cherry-picking_), and than force-push it again, so I can merge this PR.

**Pull request closed without merging**
